language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tollwerk' ]; then cd .. && eval "mv $currentfolder generator-tollwerk" && cd generator-tollwerk; fi

